version: 2

jobs:
    build:
        docker:
            -
                image: circleci/golang:1.11

        steps:
            - checkout

            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

            -
                run:
                    name: Install dependencies
                    command: go mod download

            -
                run:
                    name: Run tests
                    command: TEST_PKGS=$(echo `go list ./... | circleci tests split`) TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml make test

            -
                run:
                    name: Release
                    command: |
                        if [[ -z "$CIRCLE_TAG" ]]; then
                            echo "Skipping release";
                        else
                            make release
                        fi

            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/

            -
                store_test_results:
                    path: build/test_results/

workflows:
    version: 2
    build:
        jobs:
            -
                build:
                    filters:
                        tags:
                            only: /^v?\d+\.\d+\.\d+(-\S*)?$/
